name: Code Quality

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    name: Lint Python code
    steps:
      - uses: actions/checkout@v2
      - uses: ricardochaves/python-lint@v1.1.0
        with:
          use-pylint: true
          use-pycodestyle: true
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AlexanderMelde/yapf-action@master
        with:
          args: --verbose
