name: Tests

on: [push]

jobs:
  gotest:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: |
          make test
          coverage xml
      - name: Codecov
        uses: codecov/codecov-action@v1.0.11
        with:
          file: ./coverage.xml
